name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      placeholder: Clear and concise description.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1. Go to...
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: 0.1.0
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
