name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: extra
    attributes:
      label: Additional context
